logstash:
  build: logstash/
  # image: local/logstash-filter-geocoder
  # image: logstash:1.5
  # command: logstash -f /logstash/conf/*.conf
  command: bin/logstash -f /opt/logstash/conf/*.conf
  ports:
    - "7001:7001"
  volumes:
    - logstash/conf:/opt/logstash/conf
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch:1.6
  volumes:
    - elasticsearch/config/templates:/usr/share/elasticsearch/config/templates
    - elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"

kibana:
  image: webwurst/kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch

# eventinputform:
#   image: codeformuenster/open-events_event-input-form
#   ports:
#     - "5000:5000"
#   links:
#     - logstash

# parkleitsystemapi:
#   image: codeformuenster/parkleitsystemapi
#   command: ./scrape-loop-logstash.sh
#   links:
#     - logstash

scrapersmuenster:
 # image: scrapersmuenster_scrapersmuenster
 build: scripts/scrapers-muenster
 # dockerfile: scripts/scrapers-muenster/Dockerfile
 command: ./scrape-loop-logstash.sh
 links:
   - logstash

# scrapersdortmund:
#  # image: codeformuenster/open-events_scrapers-dortmund
#  build: scripts/scrapers-dortmund
#  command: ./scrape-loop-logstash.sh
#  links:
#    - logstash
